### ISSUE TITLE
[MongoDB] Keine Unterstützung für ReplicaSets

### ISSUE THREAD

**Issue by francois-egner** [CodingRuo/MobAPI#2]
Da ich nicht genug Zeit habe, um das Problem selber zu lösen, hier einmal ein Ticket.
Aktuell wird nur eine MongoDB-Instanz unterstützt, was in der realen Welt leider überhaupt nicht genutzt wird bzw. niemals genutzt werden sollte. Ein ReplicaSet ist der Standard, wenn MongoDB als DBMS genutzt wird. Die aktuelle Konfiguration unterstützt keine Angabe eines ReplicaSets, lediglich einen Host + Port.

**Comment by lordrepha** [comment]
Guter Einwand werde das Umsetzten.

**Comment by lordrepha1980** [comment]
Ab Version 1.2.1 enthalten. Steht zum Test bereit bitte auch die Readme unter [database connection](https://github.com/lordrepha1980/MobAPI/blob/master/README.md#database-connection-definition)  beachten.
